version: '3'

services:

  zookeeper:
    image: zookeeper:3.4.10
    volumes:
      - ./data/zookeeper/data:/data
      - ./data/zookeeper/datalog:/datalog
    ports:
      - 2181:2181

  hbase-local-master:
    image: noteax/hbase-local-master:1.2.6
    volumes:
      - ./data/hbase:/data
    ports:
      - 16000:16000
      - 16010:16010
    environment:
      - MASTER_HOSTNAME=hbase-local-master
      - ZOOKEEPER_QUORUM=zookeeper:2181
      - REGIONSERVERS=hbase-local-regionserver
    depends_on:
      - zookeeper

  hbase-local-regionserver:
    image: noteax/hbase-local-regionserver:1.2.6
    volumes:
      - ./data/hbase:/data
    ports:
      - 16020:16020
      - 16030:16030
    environment:
      - REGIONSERVER_HOSTNAME=hbase-local-regionserver
      - ZOOKEEPER_QUORUM=zookeeper:2181
    depends_on:
      - zookeeper